### ISSUE TITLE
Fabric plugin fails to execute the tasks when provided with key

### ISSUE THREAD

**Issue by prashantabkari** [cloudify-cosmo/cloudify-fabric-plugin#59]
Hi - I am using the following blueprint to bring up nginx server. The public key and private key are proper but fabric plugin doesn't seem to work. Even after providing a key it still says sudo priveleges not present

```
cloudify_host_cloud_config:
    type: cloudify.nodes.CloudInit.CloudConfig
    properties:
      resource_config:
        users:
        - name: ec2-user
          groups: sudo
          shell: /bin/bash
          sudo: ['ALL=(ALL) NOPASSWD:ALL']
          ssh-authorized-keys:
          - { get_secret: agent_key_public }

 nginx:
  type: cloudify.nodes.WebServer
  interfaces:
    cloudify.interfaces.lifecycle:
      create:
        implementation: fabric.fabric_plugin.tasks.run_commands
        inputs:
          commands:
            - apt-get install -y nginx
            - service nginx start
          fabric_env:
            user: ec2-user
            key: {get_secret : agent_key_private}
      start:
        implementation: fabric.fabric_plugin.tasks.run_task
        inputs:
          tasks_file: tasks/nginx.py
          task_name: start
          fabric_env:
            user: ec2-user
            key: {get_secret : agent_key_private}
  relationships:
     - type: cloudify.relationships.contained_in
       target: nginx_host

 nginx_host:
    type: cloudify.openstack.nodes.Server
    properties:
       openstack_config: *openstack_config
       agent_config:
         install_method: none
       server:
         image: {get_input: image}
         flavor: { get_input: flavor }
         userdata: {get_attribute: [cloudify_host_cloud_config, cloud_config ] }
       management_network_name: { get_secret: private_network_name }
    relationships:
       - type: cloudify.relationships.depends_on
         target: nginx_image
       - type: cloudify.openstack.server_connected_to_port
         target: private_network_port        
```
